Update respond.py
While im in this file, heres a small fix for eb8's issue on discord.
KeyError: ' python'
The issue was caused by the llm responding with a token starting with a space in front of the language.